//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportLogicTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Crew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Crew()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
        }
    
        public int idtbl_Crew { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public Nullable<bool> CaptainCrew { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
    }
}
