//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportLogicTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking
    {
        public int idtbl_Booking { get; set; }
        public Nullable<int> idtbl_Crew { get; set; }
        public Nullable<int> idtbl_Flight { get; set; }
    
        public virtual tbl_Flight tbl_Flight { get; set; }
        public virtual tbl_Crew tbl_Crew { get; set; }
    }
}
