//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportLogicTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Flight
    {


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Flight()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
        }


        public db_AirportEntities db;
        public int idtbl_Flight { get; set; }
        public string FlightNumber { get; set; }
        public int FromCity { get; set; }
        public int ToCity { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int idtbl_Airplane { get; set; }
        public int idtbl_Company { get; set; }
        public Nullable<bool> StopOver { get; set; }
        public string Status { get; set; }
        public Nullable<int> idRoute { get; set; }
        public Nullable<System.DateTime> ArrivalAt { get; set; }
    
        public virtual tbl_Airplane tbl_Airplane { get; set; }
        public virtual tbl_Airport tbl_Airport { get; set; }
        public virtual tbl_Airport tbl_Airport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
        public virtual tbl_Company tbl_Company { get; set; }
        public virtual tbl_Route tbl_Route { get; set; }


        public IList<tbl_Flight> getDepartures()
        {
            db_AirportEntities db = new db_AirportEntities();
            IList<tbl_Flight> flights = new List<tbl_Flight>();
            foreach (var Flight in db.tbl_Flight)
            {
                if (Flight.FromCity.Equals(1217))
                flights.Add(Flight);
            }
            return flights;
        }
        public IList<tbl_Flight> getArrives()
        {
            db_AirportEntities db = new db_AirportEntities();
            IList<tbl_Flight> flights = new List<tbl_Flight>();
            foreach (var Flight in db.tbl_Flight)
            {
                if (Flight.ToCity.Equals(937))
                    flights.Add(Flight);
            }
            return flights;
        }
        public IList<tbl_Flight> getAll()
        {
            db_AirportEntities db = new db_AirportEntities();
            IList<tbl_Flight> flights = new List<tbl_Flight>();
            foreach (var Flight in db.tbl_Flight)
            {                    
                    flights.Add(Flight);
            }
            return flights;
        }



    }
}
